# Generated by Django 2.1.5 on 2020-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
                ('happy', models.CharField(choices=[('吃饭', '吃饭'), ('喝酒', '喝酒'), ('打豆豆', '打豆豆')], max_length=10, verbose_name='兴趣')),
                ('gender', models.CharField(choices=[('1,', '男'), ('2', '女'), ('3', '未知')], max_length=10, verbose_name='性别')),
            ],
        ),
    ]
